kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: cronohub
  name: do-storage-gaia
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
